import assert from 'node:assert/strict'
import { mkdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import test, { after } from 'node:test'
import type { GptModel } from '../src/claude-models.mjs'
import { removeTempDirs, tempDir } from './helpers/tmp.mjs'

interface AgentsApi {
  renderGptAgent(model: GptModel): string
  gptAgentFilename(model: GptModel): string
  buildGptAgent(
    current: string | null,
    model: GptModel,
    ownedAfter?: string | null,
  ): { value: string | null; outcome: 'create' | 'update' | 'unchanged' | 'collision' }
  reconcileGptAgent(
    current: string | null,
    before: string | null,
    after: string,
  ): { value: string | null; outcome: 'restored' | 'already' | 'left-changed' }
  validateClaudeTarget(configDir: string, target: string): string
}
const api = async (): Promise<AgentsApi> =>
  import(new URL('../src/claude-agents.mjs', import.meta.url).href)
const model: GptModel = {
  id: 'gpt-6.1-sol',
  label: 'GPT 6.1 Sol',
  contextWindow: 100_000,
  lite: false,
  efforts: ['medium'],
}
after(removeTempDirs)

test('generated agent has only name/description/model frontmatter with an empty body', async () => {
  const { renderGptAgent, gptAgentFilename } = await api()
  const result = renderGptAgent(model)
  const parts = result.split('---\n')
  assert.equal(parts.length, 3)
  assert.equal(parts[0], '')
  assert.equal(parts[2]?.trim(), '')
  const header = parts[1]?.trim().split('\n')
  assert.ok(header)
  assert.equal(header.length, 3)
  assert.equal(header[0], `name: ${model.id}`)
  assert.equal(header[2], `model: ${model.id}`)
  assert.equal(
    JSON.parse(header[1]?.slice('description: '.length) ?? ''),
    `Use ${model.label} through AnyEngine when this model is requested.`,
  )
  assert.equal(gptAgentFilename(model), `${model.id}.md`)
  for (const field of [
    'tools:',
    'permissionMode:',
    'hooks:',
    'mcpServers:',
    'memory:',
    'systemPrompt:',
  ])
    assert.equal(result.includes(field), false)
})

test('agent description escapes quotes and YAML delimiters rather than injecting fields', async () => {
  const { renderGptAgent } = await api()
  const label = 'GPT "Sol": # {custom}'
  const result = renderGptAgent({ ...model, label })
  const description = result.split('\n')[2]
  assert.ok(description)
  assert.equal(
    JSON.parse(description.slice('description: '.length)),
    `Use ${label} through AnyEngine when this model is requested.`,
  )
  assert.equal(result.split('\n').filter((line) => line.startsWith('model:')).length, 1)
})

test('agent install refuses every unowned collision including identical generated bytes', async () => {
  const { buildGptAgent, renderGptAgent } = await api()
  const after = renderGptAgent(model)
  assert.deepEqual(buildGptAgent(null, model), { value: after, outcome: 'create' })
  for (const current of ['operator instructions\n', after])
    assert.deepEqual(buildGptAgent(current, model), { value: current, outcome: 'collision' })
  assert.deepEqual(buildGptAgent(after, model, after), { value: after, outcome: 'unchanged' })
  const edited = `${after}operator instruction\n`
  assert.deepEqual(buildGptAgent(edited, model, after), { value: edited, outcome: 'collision' })
  const revised = { ...model, label: 'Revised GPT' }
  assert.deepEqual(buildGptAgent(after, revised, after), {
    value: renderGptAgent(revised),
    outcome: 'update',
  })
})

test('agent off restores only unchanged owned bytes and keeps edited files', async () => {
  const { renderGptAgent, reconcileGptAgent } = await api()
  const after = renderGptAgent(model)
  assert.deepEqual(reconcileGptAgent(after, null, after), { value: null, outcome: 'restored' })
  assert.deepEqual(reconcileGptAgent(null, null, after), { value: null, outcome: 'already' })
  const before = 'prior owned model metadata\n'
  assert.deepEqual(reconcileGptAgent(after, before, after), { value: before, outcome: 'restored' })
  assert.deepEqual(reconcileGptAgent(before, before, after), { value: before, outcome: 'already' })
  const edited = `${after}operator edit\n`
  assert.deepEqual(reconcileGptAgent(edited, null, after), {
    value: edited,
    outcome: 'left-changed',
  })
})

test('agents reject invalid slugs and multiline/control metadata before computing paths', async () => {
  const { renderGptAgent, gptAgentFilename } = await api()
  for (const id of [
    '../escape',
    'gpt-x/escape',
    'gpt-x\\escape',
    'gpt-x[1m]',
    'gpt-x\0',
    'GPT-uppercase',
    'claude-opus',
  ]) {
    assert.throws(() => renderGptAgent({ ...model, id }))
    assert.throws(() => gptAgentFilename({ ...model, id }))
  }
  for (const label of ['', ' ', 'GPT\nhooks:', 'GPT\u2029system'])
    assert.throws(() => renderGptAgent({ ...model, label }))
})

test('target validation permits ordinary missing descendants and never writes files', async () => {
  const { validateClaudeTarget } = await api()
  const root = await tempDir('anyengine-claude-target-')
  const config = join(root, '.claude')
  const target = join(config, 'agents', `${model.id}.md`)
  assert.equal(validateClaudeTarget(config, target), target)
  mkdirSync(config)
  const settings = join(config, 'settings.json')
  writeFileSync(settings, '{"theme":"dark"}\n')
  assert.equal(validateClaudeTarget(config, settings), settings)
  assert.equal(readFileSync(settings, 'utf8'), '{"theme":"dark"}\n')
})

test('target validation rejects lexical and symlink escapes, dangling links and directories', async () => {
  const { validateClaudeTarget } = await api()
  const root = await tempDir('anyengine-claude-symlink-')
  const config = join(root, '.claude')
  const outside = join(root, 'outside')
  mkdirSync(config)
  mkdirSync(outside)
  writeFileSync(join(outside, 'target.md'), 'outside\n')
  symlinkSync(outside, join(config, 'agents'))
  symlinkSync(join(outside, 'target.md'), join(config, 'settings.json'))
  symlinkSync(join(config, 'absent.json'), join(config, 'dangling.json'))
  for (const target of [
    join(config, 'agents', `${model.id}.md`),
    join(config, 'settings.json'),
    join(config, 'dangling.json'),
    config,
    outside,
    join(root, '.claude-else', 'settings.json'),
  ])
    assert.throws(() => validateClaudeTarget(config, target))
  assert.throws(() => validateClaudeTarget('.claude', join(config, 'new.json')))
  assert.throws(() => validateClaudeTarget(config, `${config}/new\0.json`))
  assert.equal(readFileSync(join(outside, 'target.md'), 'utf8'), 'outside\n')
})

test('target validation resolves in-directory symlinks without admitting an outside target', async () => {
  const { validateClaudeTarget } = await api()
  const root = await tempDir('anyengine-claude-inside-link-')
  const config = join(root, '.claude')
  mkdirSync(join(config, 'actual'), { recursive: true })
  const actual = join(config, 'actual', 'settings.json')
  writeFileSync(actual, '{}\n')
  const target = join(config, 'settings.json')
  symlinkSync(actual, target)
  assert.equal(validateClaudeTarget(config, target), target)
  assert.equal(readFileSync(actual, 'utf8'), '{}\n')
})
